### ISSUE TITLE
Errors on empty selection

### ISSUE THREAD

**Issue by EvanK** [insightfuls/inquirer-tree-prompt#4]
Throws an error if the user just hits enter without making any selections in the tree:

```
./node_modules/inquirer-tree-prompt/index.js:317
		return typeof node.value !=='undefined' ? node.value : node.name;
		                   ^

TypeError: Cannot read properties of undefined (reading 'value')
    at TreePrompt.valueFor (./node_modules/inquirer-tree-prompt/index.js:317:22)
    at MapSubscriber.project (./node_modules/inquirer-tree-prompt/index.js:67:37)
    at MapSubscriber._next (./node_modules/inquirer-tree-prompt/node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (./node_modules/inquirer-tree-prompt/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Interface.handler (./node_modules/rxjs/dist/cjs/internal/observable/fromEvent.js:59:31)
    at Interface.emit (node:events:520:28)
    at Interface._onLine (node:readline:487:10)
    at Interface._line (node:readline:864:8)
    at Interface._ttyWrite (node:readline:1216:14)
    at ReadStream.onkeypress (node:readline:288:10)
```

I'm not sure what the expected result should be in this case; returning an empty set or displaying a warning to the user and re-displaying the tree to attempt another selection?

**Comment by geniou** [comment]
https://github.com/insightfuls/inquirer-tree-prompt/pull/10 fixed the issue for me.
